<?php

//Add a prefilter to the display of the image
add_event_handler('loc_begin_picture', 'gb_set_prefilter_add_to_pic_info');

//Fill the fiels with the data
add_event_handler('loc_begin_picture', 'gb_add_image_vars_to_template');

function gb_set_prefilter_add_to_pic_info() {
  global $template;
	$template->set_prefilter('picture', 'gb_add_to_pic_info');
}

//The prefilter
function gb_add_to_pic_info($content, &$smarty) {

  	$search = '#class="imageInfoTable">#';

    $replacement = 'class="imageInfoTable">
<div id="GB_name" class="imageInfo">
  <dt>Generated by :</dt>
  <dd>
{if $GB_INFO_TEXT}
      {$GB_INFO_TEXT}
{else}
      No generated by found
{/if}
  </dd>
</div>';

return preg_replace($search, $replacement, $content, 1);
}

//Get the content and fill with the generated by of the actual image
function gb_add_image_vars_to_template() {
  global $page, $template, $prefixeTable;

	if ( !empty($page['image_id']) ){
    $gb = GenerateByDAO::getGB($page['image_id']);
		$template->assign(
      array	(
        'GB_INFO_TEXT' => $gb
      )
    );
	}
}

?>
