<?php
//  Add a field of the modification form by a prefilter
add_event_handler('loc_end_element_set_unit', 'gb_set_prefilter_batch_single', 55 );

// Add a handler to get the return data of the form
add_event_handler('loc_begin_element_set_unit', 'gb_batch_single_submit', 50 );


function gb_set_prefilter_batch_single() {
  global $template;
  $template->set_prefilter('batch_manager_unit', 'gb_batch_single');
}

// The prefilter
function gb_batch_single($content, &$smarty) {
  $search = "#<td><strong>{'Creation date'#";

	$replacement = '<td><strong>Generated by</strong></td>
		<td>
			<input type="text" id="generatedby-{$element.ID}" name="generatedby-{$element.ID}">
			</input>
		</td>
	</tr>

	<tr>
		<td><strong>{\'Creation date\'';

  return preg_replace($search, $replacement, $content);
}

function gb_batch_single_submit() {
  if (isset($_POST['submit'])) {
    $collection = explode(',', $_POST['element_ids']);
    foreach ($collection as $image_id) {
      $value = pwg_db_real_escape_string($_POST['generatedby-'.$image_id]); //Get the modificate field for each image
      if ($value != "")
        GenerateByDAO::delete($image_id); //delete actual GB for this image
        GenerateByDAO::insert($value, $image_id); //add a GB for this image
    }
  }
}

?>
