<?php
//Set the modification action
add_event_handler('loc_end_element_set_global', 'gb_batch_global');

//Get the modification and change database
add_event_handler('element_set_global_action', 'gb_batch_global_submit', 50, 2);


function gb_batch_global() {
  global $template;

  $template->set_filename('gb_batch_global', GENERATEAWESOME_PATH.'/batch_global.tpl');

  $template->append('element_set_global_plugins_actions', array(
  'ID' => 'generated_by',				// ID of the batch manager action
  'NAME' => l10n('Set Generated By'),	// Description of the batch manager action
  'CONTENT' => $template->parse('gb_batch_global', true) // File to display
  ));
}

function gb_batch_global_submit($action, $collection) {
  if ($action == "generated_by") { // If the action is choosen
    $value = pwg_db_real_escape_string($_POST['image_generated_by']);
    if ($value != "") {
      foreach ($collection as $image_id) { //foreach image choosen
        GenerateByDAO::delete($image_id); //delete actual GB for this image
        GenerateByDAO::insert($value, $image_id); //add a GB for this image
      }
    }
  }
}

?>
