<?php

if (!defined('PHPWG_ROOT_PATH')) die('Hacking attempt!');

add_event_handler('loc_begin_admin', 'GB_set_prefilter_modify', 50 );
add_event_handler('loc_begin_admin_page', 'GB_modify_submit', 45 );

function GB_set_prefilter_modify()
{
	global $template;
	$template->set_prefilter('picture_modify', 'GB_modify');
}

function GB_modify($content, &$smarty)
{
	$search = "#<strong>{'Creation date'#"; // Not ideal, but ok for now :)

	// We use the <tr> from the Creation date, and give them a new <tr>
	$replacement = '<strong>Generated By</strong>
		<br>
			<input type="text" id="gb" name="generatedBy">
			</input>
		</p>

	</p>
  <p>
		<strong>{\'Creation date\'';

    return preg_replace($search, $replacement, $content);
}

function GB_modify_submit() {
  if (isset($_GET['page']) and 'photo' == $_GET['page'] and isset($_GET['image_id'])){
    if (isset($_POST['submit']))  {
      // The data from the submit
      $image_id = $_GET['image_id'];
      $value = $_POST['generatedBy'];

      GenerateByDAO::delete($image_id);
      GenerateByDAO::insert($value, $image_id);
    }
  }
}

?>
